### Theme ###
remote_theme: pmarsceill/just-the-docs

### Title ###
title: Web Dev
# Lang
lang: ru
# URL
permalink: pretty

aux_links:
  "Česnakas on GitHub":
    - "//github.com/cesnakas"

aux_links_new_tab: true

gh_edit_link: false

search_enabled: true
search:
  lang:
    - en
    - ru

plugins:
  - jekyll-seo-tag
  - search:
      lang:
        - en
        - ru

sass:
  style: :compressed
